apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: azure-function-app
  title: Azure Function App
# type: Environment
# description: ./readme.md

# configuration:
# isolation: ResourceGroup

spec:
  owner: group:backstage-admins
  type: service

  parameters:
    - title: New Function App
      description: 'foo'
      type: object
      required:
        - functionAppRuntime
        - storageAccountType
      properties:
        functionAppRuntime:
          name: Function App Runtime
          title: Function App Runtime
          type: string
          default: dotnet
          enum:
            - node
            - dotnet
            - java
        storageAccountType:
          name: Storage Account Type
          title: Storage Account Type
          type: string
          default: Standard_LRS
          enum:
            - Standard_LRS
            - Standard_GRS
            - Standard_RAGRS
        httpsOnly:
          name: HTTPS only
          title: HTTPS only
          type: boolean
          default: true
  steps:
    - id: fetch-arm
      name: Fetch Base
      action: fetch:plain
      input:
        url: ./azuredeploy.json
