apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-thing
  description: A Component to test stuff with
  annotations:
    github.com/project-slug: 'backstage/backstage'
spec:
  type: service
  lifecycle: production
  owner: user:guest
