apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - 8-vCPU
    - 32GB-RAM
    - 512GB-Storage
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    msft.dev/resource-type: dev-box
    msft.dev/project-slug: ${{values.project | dump}}
spec:
  type: dev-box
  lifecycle: production
  owner: ${{values.owner | dump}}