apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Alpha Testing
  description: Dev Box
  annotations:
    msft.dev/org-slug: 'contoso'
    msft.dev/project-slug: 'project-alpha'
    msft.dev/resource-type: 'dev-box'
spec:
  type: service
  lifecycle: production
  owner: colbyw
